services:
  ai:
    build: ./ai
    volumes:
      - ./ai/src:/app/src
      - ~/.cache/pip:/root/.cache/pip
      - ./.env:/app/.env
    ports:
      - "9000:9000"
    env_file:
      - .env
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --log-level debug
    depends_on:
      - ai
    environment:
      - AI_URL=http://ai:9000

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    env_file: .env
    depends_on:
      - backend
